#!/bin/bash
dotnet tool restore
dotnet paket restore
npm install
mkdir -p wwwroot/assets
cp node_modules/bulma/css/bulma.min.css wwwroot/assets/
dotnet build
dotnet publish -r linux-x64 --no-self-contained
