#!/bin/bash
version="$(git describe --always)"

pushd src/Client/ || exit
yarn build
popd || exit
rm -r src/CLI/wwwroot/
mkdir -p src/CLI/wwwroot/
cp -R src/Client/dist/* src/CLI/wwwroot/

rm -rf dist
mkdir dist

dotnet publish -c Release -r linux-x64 --no-self-contained -o dist src/CLI/
mv dist/manga "dist/manga-$version-linux-x64"
dotnet publish -c Release -r linux-x64 --self-contained -o dist src/CLI/
mv dist/manga "dist/manga-$version-linux-x64-self-contained"

dotnet publish -c Release -r win-x64 --no-self-contained -o dist src/CLI/
mv dist/manga.exe "dist/manga-$version-win-x64.exe"
dotnet publish -c Release -r win-x64 --self-contained -o dist src/CLI/
mv dist/manga.exe "dist/manga-$version-win-x64-self-contained.exe"

sha256sum dist/* > "dist/manga-$version-checksums.txt"
